-- CRIAR O BANCO DE DADOS
CREATE DATABASE IFSP;

-- SELECIONAR O BANCO DE DADOS
USE IFSP;

-- CRIAR TABELA CIDADE
CREATE TABLE CIDADE(id INT PRIMARY KEY AUTO_INCREMENT, nome VARCHAR(45) NOT NULL, estado CHAR(2) NOT NULL);

-- CRIAR TABELA CLIENTE
CREATE TABLE CLIENTE(
    id INT PRIMARY KEY AUTO_INCREMENT, 
    nome VARCHAR(45) NOT NULL, 
    email VARCHAR(55) NOT NULL,
    FOREIGN KEY (id) REFERENCES CIDADE (id),
    endereco VARCHAR(45),
    bairro VARCHAR(45),
    numero INT,
    data_nasc DATE
    );